### ISSUE TITLE
compiler not working

### ISSUE THREAD

**Issue by jathinreddy** [vineetchoudhary/TurboCPP#5]
my compiler is not working.Please help me to solve the problem

**Comment by vineetchoudhary** [comment]
hi, what the issue you are facing? Please tell me in the details.

**Comment by vineetchoudhary** [comment]
This issue has been closed because there has been no response to our request for more information from the author. With only the information that is currently on the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
